### ISSUE TITLE
Error code after update 9.1.1 to 9.1.2

### ISSUE THREAD

**Issue by penbox-ad** [concretecms-community-store/community_store#693] opened 2022-10-14 13:33 UTC
I have installed Store v.2.4.6 with Concrete v.9.1.1 (PHP is 7.4.33) and I tried to update Concrete to 9.1.2 and then comes this error message:

Entity 'Concrete\Package\CommunityStore\Entity\Attribute\Key\StoreOrderKey' has to be part of the discriminator map of 'Concrete\Core\Entity\Attribute\Key\Key' to be properly mapped in the inheritance hierarchy. Alternatively you can make 'Concrete\Package\CommunityStore\Entity\Attribute\Key\StoreOrderKey' an abstract class to avoid this exception from occurring.

I had to return the site from backup.
What this error means, do I have to update the Store to a newer version first or modify code somehow?

Concrete 9.1.2 version supports more webp images and that's why I need to update Concrete. Any idea how to go on?

**Comment by Mesuva** [comment] 2022-10-14 15:53
This is an ongoing issue I've not been able to work out the cause of.
For example, you'll see this issue mentioned in the second half here: https://github.com/concretecms-community-store/community_store/issues/683
And here as well: https://github.com/concretecms-community-store/community_store/issues/556
And here: https://github.com/concretecms-community-store/community_store/issues/422
And here: https://github.com/concretecms-community-store/community_store/issues/439

In all those cases, it's either resolved itself, or a deep dive hasn't really discovered anything.

My thinking for a while is that it's been other add-ons that load earlier than Community Store, changing the 'boot' process of Concrete in some way, and then it gets stuck not being able to load Community Store classes.

I don't think it's something that will be resolved by an upgrade, but 2.4.6 isn't that far off the latest release anyway, so it wouldn't hurt to try on a scratch version.

I'd see if you can temporarily disable some other add-ons via the Packages table, run a cache clear and a 'Refresh Entities' via /index.php/dashboard/system/environment/entities, to see if you can clear the error, then re-enable other add-ons.

**Comment by penbox-ad** [comment] 2022-10-26 06:46
Okey, seems that other users have had the same error.
You were right updating the Community Store first didn't help – same error.

**Comment by mdius** [comment] 2022-11-04 11:48
I just had the same issue upgrading from 9.1.2 to 9.1.3, then I clicked Re-Run Upgrade Script and that seemed to work this time for me.

**Comment by mdius** [comment] 2022-11-07 17:19
Had this error on my clean install test site and I manually turned on Database Entities - Doctrine Development Mode and then re-run script, and that worked for that site.

**Comment by penbox-ad** [comment] 2022-11-09 13:49
Mdius, this sounds promising advice to try. Error links to Entities, so I'll click first on Database Entities and then try to upgrage. If error > click Re-Run script. The site is live I'll have to wait for a peaceful moment to test this.

**Closed** 2023-01-27 14:35 UTC
